<a href="https://colab.research.google.com/github/kurek0010/neural-network-course/blob/master/03_keras/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Model sekwencjny (Sequential Model):
1. [Wprowadzenie - pierwszy model](#a0)
2. [Funkcje aktywacji](#a1)
3. [Kompilacja modelu](#a2)
4. [Trenowanie modelu](#a3)
5. [Przykład - klasyfikacja binarna](#a4)
6. [Przykład - klasyfikacja wieloklasowa](#a5)
7. [Przykład - regresja](#a6)



Konfiguracja środowiska


In [ ]:
# Przygotowanie środowiska do pracy z Tensorflow 2.0.
# Jeśli otrzymasz błąd podczas instalacji Tensorflow uruchom tę komórkę raz jeszcze.

!pip uninstall -y tensorflow
!pip install -q tensorflow==2.0.0

Found existing installation: tensorflow 2.0.0
Uninstalling tensorflow-2.0.0:
  Successfully uninstalled tensorflow-2.0.0


In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.18.0'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [2]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

<Sequential name=sequential, built=False>


Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*

In [3]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Wyświetlenie podsumowania modelu: metoda *.summary()*

In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

Dodanie kolejnej warstwy

In [5]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [6]:
from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -2.496165 -2.496165
1 -2.435727 -2.435727
2 -2.100131 -2.100131
3 -1.970407 -1.970407
4 -1.864136 -1.864136

In [7]:
px.line(data, x='data', y='linear', width=800, range_y=[-2, 2])

In [8]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -2.496165  0.076127
1 -2.435727  0.080489
2 -2.100131  0.109084
3 -1.970407  0.122345
4 -1.864136  0.134222

In [9]:
px.line(data, x='data', y='sigmoid', width=800, range_y=[-0.5, 1.5])

In [10]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -2.496165   0.0
1 -2.435727   0.0
2 -2.100131   0.0
3 -1.970407   0.0
4 -1.864136   0.0

In [11]:
px.line(data, x='data', y='relu', width=800, range_y=[-0.5, 1.5])

In [12]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -2.496165 -0.986512
1 -2.435727 -0.984792
2 -2.100131 -0.970460
3 -1.970407 -0.961876
4 -1.864136 -0.953060

In [13]:
px.line(data, x='data', y='tanh', width=800, range_y=[-1.5, 1.5])

In [14]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/))
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

In [15]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [16]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [17]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [18]:
data[:3]

array([[-2.17455367e-01, -2.15482613e-01, -2.11012032e+00,
        -5.06586949e-02,  8.13374333e-01, -1.09107118e+00,
        -5.96797595e-01, -1.33504654e+00, -5.15013499e-01,
         4.53800138e-01,  1.78597644e+00,  1.70590763e+00,
        -1.34383190e+00, -1.83140652e+00,  1.14167885e+00,
        -8.19653101e-02, -2.06954955e+00,  7.27137968e-01,
         3.48138218e-01,  4.51499420e-01, -1.78704921e+00,
         1.89427716e+00, -1.02632411e+00, -4.48424341e-01,
        -1.03823827e+00, -1.30994788e+00,  8.83925445e-02,
         1.65847141e+00,  3.09494758e-01,  4.06204913e-01,
        -6.31074995e-01, -8.47757389e-01,  6.42155365e-01,
        -3.14896278e-01,  3.05125920e-02, -6.00264750e-01,
        -2.43417134e-01,  1.43269088e-01,  1.70561683e-01,
        -8.40648649e-01, -2.42293112e-01,  1.42955793e+00,
         4.98151107e-01,  1.57658712e-01,  3.23051665e-01,
         1.88929795e+00,  6.09192676e-01, -5.89255240e-01,
         3.48575465e-01,  2.84370870e-01,  2.05118862e+0

In [19]:
labels[:10]

array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0]])

In [20]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4614 - loss: 1.0201
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5475 - loss: 0.7675 
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5957 - loss: 0.6846 
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6467 - loss: 0.6282
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6946 - loss: 0.5925 
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7265 - loss: 0.5658 
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7802 - loss: 0.5155 
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7863 - loss: 0.4969
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8346 - loss: 0.4665 
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8386 - loss: 0.4483 
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8677 - loss: 0.4207 
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8

In [21]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4933 - loss: 0.8189
Epoch 2/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6005 - loss: 0.6812 
Epoch 3/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6099 - loss: 0.6509
Epoch 4/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6710 - loss: 0.5978
Epoch 5/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7166 - loss: 0.5611
Epoch 6/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7383 - loss: 0.5377
Epoch 7/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8128 - loss: 0.4906
Epoch 8/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8158 - loss: 0.4705
Epoch 9/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8477 - loss: 0.4435
Epoch 10/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8667 - loss: 0.4238
Epoch 11/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8852 - loss: 0.3913
Epoch 12/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8922 - l

In [22]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5148 - loss: 0.8007 - val_accuracy: 0.5550 - val_loss: 0.7414
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5849 - loss: 0.6946 - val_accuracy: 0.5350 - val_loss: 0.7492
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6043 - loss: 0.6478 - val_accuracy: 0.5400 - val_loss: 0.7592
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6814 - loss: 0.5994 - val_accuracy: 0.5000 - val_loss: 0.7704
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7650 - loss: 0.5387 - val_accuracy: 0.5050 - val_loss: 0.7859
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7647 - loss: 0.5198 - val_accuracy: 0.4850 - val_loss: 0.7996
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7713 - loss: 0.5017 - val_accuracy: 0.4800 - val_loss: 0.8134
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8197 - loss: 0.4554 - val_accuracy: 0.4800 - val_loss

In [23]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [24]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [25]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [26]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.4703 - loss: 0.8527 - val_accuracy: 0.4800 - val_loss: 0.8558
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5231 - loss: 0.7424 - val_accuracy: 0.4650 - val_loss: 0.8303
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5742 - loss: 0.6761 - val_accuracy: 0.4800 - val_loss: 0.8194
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6582 - loss: 0.6220 - val_accuracy: 0.4750 - val_loss: 0.8163
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6944 - loss: 0.5991 - val_accuracy: 0.4750 - val_loss: 0.8169
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7474 - loss: 0.5565 - val_accuracy: 0.4900 - val_loss: 0.8225
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7856 - loss: 0.5139 - val_accuracy: 0.4900 - val_loss: 0.8281
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7971 - loss: 0.5063 - val_accuracy: 0.4950 - val_loss

In [27]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [28]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([[0.4080665 ],
       [0.33631232],
       [0.4364555 ],
       [0.7463847 ],
       [0.22754781]], dtype=float32)

In [29]:
model.predict_proba(test_data)

AttributeError: 'Sequential' object has no attribute 'predict_proba'

In [ ]:
model.predict_classes(test_data)

array([[1],
       [1],
       [0],
       [0],
       [0]], dtype=int32)

### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa

In [30]:
data = np.random.random((1000, 150))
labels = np.random.randint(10, size=(1000, 1))

In [31]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [32]:
data[:3]

array([[0.85465236, 0.04936831, 0.67303104, 0.54910103, 0.78686908,
        0.93059727, 0.27384622, 0.39541587, 0.89459698, 0.37257643,
        0.50568017, 0.20860904, 0.67196227, 0.57454911, 0.60012715,
        0.29861054, 0.90202457, 0.07670919, 0.10587148, 0.97899638,
        0.45103783, 0.61695985, 0.24412775, 0.11785517, 0.20325464,
        0.04556032, 0.20510833, 0.64071808, 0.10528428, 0.73054985,
        0.8853233 , 0.61756067, 0.30680413, 0.78976824, 0.68028702,
        0.64809607, 0.00968087, 0.26843699, 0.57802901, 0.61530071,
        0.85368689, 0.15867239, 0.36604902, 0.42015611, 0.59420563,
        0.30898306, 0.44009701, 0.62185433, 0.01252955, 0.21539588,
        0.51378579, 0.91518214, 0.37107645, 0.3621256 , 0.77394931,
        0.56206256, 0.10993198, 0.27907786, 0.23279003, 0.97891313,
        0.80820536, 0.99050805, 0.0882032 , 0.26101723, 0.68268843,
        0.54738213, 0.19150625, 0.7699633 , 0.36866596, 0.41225878,
        0.48940566, 0.38672276, 0.88347764, 0.03

In [33]:
labels[:10]

array([[5],
       [6],
       [8],
       [3],
       [0],
       [1],
       [2],
       [1],
       [5],
       [6]])

In [34]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [35]:
labels[1]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [36]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.1039 - loss: 2.4155 - val_accuracy: 0.0950 - val_loss: 2.3324
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1197 - loss: 2.2955 - val_accuracy: 0.1050 - val_loss: 2.3224
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1072 - loss: 2.3027 - val_accuracy: 0.1000 - val_loss: 2.3344
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1344 - loss: 2.2973 - val_accuracy: 0.0850 - val_loss: 2.3326
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1705 - loss: 2.2633 - val_accuracy: 0.1050 - val_loss: 2.3285
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1724 - loss: 2.2493 - val_accuracy: 0.0850 - val_loss: 2.3358
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1895 - loss: 2.2351 - val_accuracy: 0.1100 - val_loss: 2.3410
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1865 - loss: 2.2274 - val_accuracy: 0.1000 - val_loss

In [37]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[0.08939333, 0.06921118, 0.07829586, 0.09378143, 0.14257333,
        0.10579226, 0.09260089, 0.05203894, 0.15388207, 0.12243079],
       [0.1168538 , 0.1257884 , 0.07286587, 0.15082005, 0.11915925,
        0.07803196, 0.06734985, 0.07909814, 0.09764364, 0.09238901],
       [0.07375192, 0.13546172, 0.04945258, 0.2369684 , 0.05323624,
        0.12755221, 0.06467468, 0.15757275, 0.03062264, 0.07070695],
       [0.24215865, 0.0748915 , 0.03920615, 0.04184826, 0.05715281,
        0.12245377, 0.08084358, 0.05930372, 0.08768804, 0.19445355],
       [0.10937313, 0.12471735, 0.11061639, 0.10571697, 0.08377603,
        0.12095134, 0.07201751, 0.06918472, 0.124481  , 0.07916551],
       [0.09516133, 0.12636109, 0.15861583, 0.14759047, 0.10994699,
        0.11741465, 0.039161  , 0.12419934, 0.04544918, 0.03610003],
       [0.09919964, 0.15338205, 0.05084737, 0.05571334, 0.07497195,
        0.17978504, 0.05885242, 0.08648364, 0.10837263, 0.13239196],
       [0.03293865, 0.11753402, 0.0921359

In [38]:
model.predict_classes(test_data)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

### <a name='a6'></a> Przykład - regresja

In [39]:
data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

In [40]:
data[:3]

array([[0.29129199, 0.19312031, 0.67530931, 0.00596072, 0.98671129,
        0.99466445, 0.86953627, 0.48141277, 0.0483958 , 0.99040744,
        0.5495886 , 0.99803403, 0.41351982, 0.93912383, 0.31821712,
        0.45663769, 0.5134769 , 0.00378254, 0.8505591 , 0.73733309,
        0.46175081, 0.98573285, 0.74206747, 0.90484136, 0.23793129,
        0.30366443, 0.80829442, 0.84451807, 0.31151225, 0.29227488,
        0.8062832 , 0.58690314, 0.15690017, 0.41788009, 0.60056838,
        0.64620713, 0.62865277, 0.37796466, 0.04059206, 0.83506048,
        0.56504624, 0.60963764, 0.59792404, 0.59117002, 0.12449723,
        0.06731811, 0.46111461, 0.39816776, 0.76732047, 0.76741686,
        0.26241848, 0.35644136, 0.44266812, 0.50379914, 0.14217964,
        0.5100677 , 0.2635234 , 0.13895185, 0.97828649, 0.38513448,
        0.67597923, 0.01552302, 0.24239518, 0.31198423, 0.16685036,
        0.31482838, 0.72358633, 0.77979596, 0.19829449, 0.23002291,
        0.88637949, 0.22886004, 0.45326528, 0.33

In [41]:
labels[:10]

array([41.03180959, 23.34363212, 37.44372518,  9.19821167, 46.07573189,
       17.32692301, 46.20952119, 26.89714331, 18.57570366,  2.50500758])

In [42]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 675.7253 - val_loss: 463.5762
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 434.4210 - val_loss: 296.6201
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 275.1500 - val_loss: 217.6838
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 225.2116 - val_loss: 209.9437
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 215.4683 - val_loss: 210.3047
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 195.2787 - val_loss: 210.6543
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 206.3850 - val_loss: 210.2857
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 206.5748 - val_loss: 210.5627
Epoch 9/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 195.6758 - val_loss: 210.6525
Epoch 10/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 203.4582 - val_loss: 210.0862
Epoch 11/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 206.0648 - val_loss: 210.1362
Epoch 12/30
25/25 ━━━━━━━━━━━━

In [43]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 21.6403 - mse: 667.2689 - val_loss: 16.4527 - val_mse: 416.3295
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.4221 - mse: 399.5563 - val_loss: 13.5460 - val_mse: 273.0226
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.2625 - mse: 255.1429 - val_loss: 12.3876 - val_mse: 215.1621
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.8025 - mse: 228.4299 - val_loss: 12.3094 - val_mse: 210.2119
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.0074 - mse: 226.2860 - val_loss: 12.3102 - val_mse: 209.9924
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.0346 - mse: 224.5699 - val_loss: 12.3116 - val_mse: 210.5903
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.4589 - mse: 213.2127 - val_loss: 12.3095 - val_mse: 210.2366
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.4136 - mse: 206.3264 - val_loss: 12.3082 - val_mse: 210.2525
Epoch 9/30
25/25 ━━━━━━

In [44]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[22.540384],
       [22.678303],
       [25.422924],
       [23.781559],
       [23.322428],
       [25.104668],
       [26.870668],
       [23.297224],
       [22.367348],
       [27.445112]], dtype=float32)